### ISSUE TITLE
Doesn't build with maven 3.1.1

### ISSUE THREAD

**Issue by bootstraponline** [selendroid/selendroid#270]
> [INFO] --- android-maven-plugin:3.6.0:generate-sources (default-generate-sources) @ android-driver-app ---
> [WARNING] Error injecting: com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo
> java.lang.NoClassDefFoundError: Lorg/sonatype/aether/RepositorySystem;
> 
> $ mvn --version
> Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 11:22:22-0400)

[maven-android-plugin](https://code.google.com/p/maven-android-plugin/) should be updated to the latest version.
