### ISSUE TITLE
My app crashes while starting using Selendroid 0.11+

### ISSUE THREAD

**Issue by PavelKulagin** [selendroid/selendroid#693]
My app is a client of a social network. I have some limitations to show logs of my app, so I tried to change some class paths in logs.
I use Selendroid since 0.9 version and 0.10 works fine for my app too. But after releasing 0.11 (and I tried to use 0.12 too) my app started to crash after login. All builds of my app work with 0.10 perfectly. But when I try to use 0.11 it breaks everything. First, I install my app resigned with debug certificate. Then I launch Selendroid, it installs selendroid-server on device. After that, if I try to start an app manually, from device, it works fine. But when I (or Selendroid) launch it with 
adb.exe -s %deviceid% shell am instrument -e main_activity ru.my.app.ui.activity.main.MyAppActivity -e server_port 8082 io.selendroid.ru.my.app/io.selendroid.ServerInstrumentation
it starts an app, then I enter login and password, and when I tap "login", app crashes. I attach crash log at the bottom of this issue.
I showed this crash log to our developers, they were very suprised that it crashes with NoClassDefFoundError cause there shouldn't be any problem with this class, and it works perfectly when I try to login manually, without ServerInstrumentation thing.
So, all this situation makes me think that it is something wrong with io.selendroid.ServerInstrumentation and it definetely started with the release of 0.11

Crash log: 11-10 13:29:31.336: D/ru.my.app.services.app.MyAppService(30322): onCreate (32): Service create
11-10 13:29:31.351: D/ru.my.app.services.app.MyAppService(30322): onHandleIntent (55): Handle ru.my.app.services.processors.login.LoginProcessorNew command
11-10 13:29:31.359: D/ru.my.app.services.transport.JsonSessionTransportProvider(30322): <init> (71): >>> Initializing JsonSessionTransportProvider...
11-10 13:29:31.359: I/dalvikvm(30322): Rejecting re-init on previously-failed class Lru/my/app/services/transport/AuthSessionDataStore; v=0x0
11-10 13:29:31.383: W/dalvikvm(30322): threadid=50: thread exiting with uncaught exception (group=0x40e4b1f8)
11-10 13:29:31.383: W/System.err(30322): java.lang.NoClassDefFoundError: ru/my/app/services/transport/AuthSessionDataStore
11-10 13:29:31.383: W/System.err(30322): 	at ru.my.app.services.transport.JsonSessionTransportProvider.<init>(JsonSessionTransportProvider.java:74)
11-10 13:29:31.383: W/System.err(30322): 	at ru.my.app.services.transport.JsonSessionTransportProvider.getInstance(JsonSessionTransportProvider.java:63)
11-10 13:29:31.383: W/System.err(30322): 	at ru.my.app.services.app.MyAppService.createProcessorByCommandName(MyAppService.java:70)
11-10 13:29:31.383: W/System.err(30322): 	at ru.my.app.services.app.MyAppService.onHandleIntent(MyAppService.java:58)
11-10 13:29:31.383: W/System.err(30322): 	at ru.my.app.services.base.ThreadedService$1.run(ThreadedService.java:23)
11-10 13:29:31.383: W/System.err(30322): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-10 13:29:31.383: W/System.err(30322): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-10 13:29:31.383: W/System.err(30322): 	at java.lang.Thread.run(Thread.java:856)
11-10 13:29:31.383: W/FlurryAgent(30322): Error logged: uncaught
11-10 13:29:31.383: W/FlurryAgent(30322): Ending session
11-10 13:29:31.437: W/ResourceType(30322): No known package when getting name for resource number 0xffffffff
11-10 13:29:31.437: W/ResourceType(30322): No known package when getting name for resource number 0xffffffff
11-10 13:29:31.437: W/ResourceType(30322): No known package when getting name for resource number 0xffffffff
11-10 13:29:31.508: I/ActivityManager(1466): Process ru.my.app (pid 30322) has died.
11-10 13:29:31.508: W/ActivityManager(1466): Scheduling restart of crashed service ru.my.app/.services.app.MyAppService in 5000ms
11-10 13:29:31.508: W/ActivityManager(1466): Force removing ActivityRecord{41ecc210 ru.my.app/.ui.activity.LoginActivity}: app died, no saved state
11-10 13:29:31.515: D/InputDispatcher(1466): Focus left window: Window{42297018 ru.my.app/ru.my.app.ui.activity.LoginActivity paused=false}
11-10 13:29:31.515: I/WindowManager(1466): WIN DEATH: Window{42297018 ru.my.app/ru.my.app.ui.activity.LoginActivity paused=false}
11-10 13:29:31.523: W/ActivityManager(1466): Crash of app ru.my.app running instrumentation ComponentInfo{io.selendroid.ru.my.app/io.selendroid.ServerInstrumentation}
11-10 13:29:31.523: I/ActivityManager(1466): Force stopping package ru.my.app uid=10005

**Comment by PavelKulagin** [comment]
Issue cannot be reproduced in version 0.13, thanks a lot!
