### ISSUE TITLE
Exception executing findElement in a webview on API level 10 device (OS 2.3.3)

### ISSUE THREAD

**Issue by vicwomg** [selendroid/selendroid#83]
The following works on my webview  running 4.1 and 4.2:

driver.switchTo().window("WEBVIEW");  
WebElement closeButton = driver.findElement(By.xpath("//div[@onclick='clickClose()']"));
closeButton.click()

However, when I run on devices or emulators on API level 10, I get an exception while executing findElement on the webview:

TypeError: Result of expression 'd.evaluate' [undefined] is not a function.

Full stack trace below:

I/System.out( 2440): find element command using 'xpath' with selector '//div[@onclick='clickClose()']'.
I/System.out( 2440): convertToJsArgs: "xpath"
I/System.out( 2440): convertToJsArgs: "//div[@onclick='clickClose()']"
I/System.out( 2440): convertToJsArgs: "xpath","//div[@onclick='clickClose()']"
I/System.out( 2440): jsResult: {"status":32,"value":{"message":"Unable to locate an element with the xpath expression //div[@onclick='clickClose()'] because of the following error:\nTypeError: Result of expression 'd.evaluate' [undefined] is not a function."}}
I/System.out( 2440): Error occured while handling reuqest.
W/System.err( 2440): io.selendroid.exceptions.SelendroidException: {"message":"Unable to locate an element with the xpath expression \/\/div[@onclick='clickClose()'] because of the following error:\nTypeError: Result of expression 'd.evaluate' [undefined] is not a function."}
W/System.err( 2440):    at io.selendroid.server.model.SelendroidWebDriver.executeAtom(SelendroidWebDriver.java:159)
W/System.err( 2440):    at io.selendroid.server.model.SelendroidWebDriver.executeAtom(SelendroidWebDriver.java:130)
W/System.err( 2440):    at io.selendroid.server.model.DefaultSelendroidDriver$WebviewSearchScope.lookupElement(DefaultSelendroidDriver.java:406)
W/System.err( 2440):    at io.selendroid.server.model.internal.AbstractWebElementContext.findElementByXPath(AbstractWebElementContext.java:201)
W/System.err( 2440):    at io.selendroid.server.model.internal.AbstractWebElementContext.findElement(AbstractWebElementContext.java:144)
W/System.err( 2440):    at io.selendroid.server.model.By$ByXPath.findElement(By.java:231)
W/System.err( 2440):    at io.selendroid.server.model.DefaultSelendroidDriver.findElement(DefaultSelendroidDriver.java:108)
W/System.err( 2440):    at io.selendroid.server.handler.FindElement.handle(FindElement.java:46)
W/System.err( 2440):    at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:224)
W/System.err( 2440):    at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:81)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
W/System.err( 2440):    at io.selendroid.server.inspector.InspectorServlet.handleHttpRequest(InspectorServlet.java:53)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
W/System.err( 2440):    at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
W/System.err( 2440):    at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
W/System.err( 2440):    at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
W/System.err( 2440):    at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
W/System.err( 2440):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
W/System.err( 2440):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
W/System.err( 2440):    at java.lang.Thread.run(Thread.java:1019)
I/System.out( 2440): replyWithServerError 500
